### ISSUE TITLE
 NUKI HTTPError code: 404 

### ISSUE THREAD

**Issue by schurgan** [heggink/domoticz-nuki#14]
Hello heggink, I bought Nuki 3.0 and immediately installed your plugin. When I open or close the lock, it is displayed in Domoticz. But I can't open or close it from Domoticz with On-Button. The following error occurs: NUKI HTTPError code: 404
What I have done wrong?
Thank you for your help

**Comment by heggink** [comment]
Hi, I caught a flu so am a bit tied for time. Can you switch on debug and send me the logs? I don't have a v3 but will try to help.

**Comment by schurgan** [comment]
Hello, thanks for quick reply.  Everything is fine.  No idea why I had the error yesterday.  Thank you for your good work.

**Comment by heggink** [comment]
Good to hear. Happy to be of help.


Herman Eggink
________________________________
